import React, { useEffect, useState } from 'react';
import { BookOpen, ImagePlus, Search, ShieldCheck, Sparkles, Users } from 'lucide-react';
import Navbar from './Navbar';
import { getSupabaseBrowserClient } from './services/supabase/client.js';
import { searchAdminPlayers, searchSynopsisTargets, updateCardContent, updateCollectionContent, updateFormContent, updatePlayerStatus } from './services/supabase/adminService.js';

const STATUS = { active: 'Ativo', suspended: 'Suspenso', banned: 'Banido' };
const CARD_KINDS = [['character', 'Personagens'], ['item', 'Itens'], ['boss', 'Bosses']];
const slug = (value) => String(value || 'item').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'item';

async function uploadImage(entity, file, type) {
  if (!file) return entity.imageUrl || '';
  const supabase = getSupabaseBrowserClient();
  const collection = String(entity.collectionId || (type === 'collection' ? entity.id : 'MULTIVERSE')).toUpperCase();
  const extRaw = (file.name.split('.').pop() || 'jpg').toLowerCase();
  const ext = extRaw === 'jpeg' ? 'jpg' : extRaw;
  const path = `deckverse-media/${collection}/${type}/${collection}__${type}__${slug(entity.name)}.${ext}`;
  const { error } = await supabase.storage.from('cards').upload(path, file, { upsert: true, contentType: file.type, cacheControl: '31536000' });
  if (error) throw error;
  return supabase.storage.from('cards').getPublicUrl(path).data.publicUrl;
}

function Notice({ notice }) {
  if (!notice) return null;
  return <div className={`rounded-xl border p-3 text-xs ${notice.error ? 'border-destructive/30 bg-destructive/10 text-destructive' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'}`}>{notice.text}</div>;
}

function SearchBox({ query, setQuery, load, placeholder }) {
  return <div className="flex gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder={placeholder} className="h-11 min-w-0 flex-1 rounded-xl border border-border bg-background px-3 text-sm"/><button onClick={load} aria-label="Buscar" className="h-11 w-11 rounded-xl bg-primary text-primary-foreground"><Search className="mx-auto h-4 w-4"/></button></div>;
}

function Editor({ selected, draft, setDraft, active, setActive, file, setFile, busy, notice, save, title = 'Registro' }) {
  if (!selected) return <section className="rounded-3xl border border-border bg-card"><div className="flex min-h-[560px] items-center justify-center p-6 text-center text-muted-foreground"><div><ImagePlus className="mx-auto h-10 w-10 opacity-30"/><h3 className="mt-4 text-xl font-black text-foreground">Selecione um registro</h3><p className="mt-2 text-sm">A imagem, sinopse e publicação ficam editáveis aqui.</p></div></div></section>;
  return <section className="rounded-3xl border border-border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row"><div className="h-32 w-24 overflow-hidden rounded-2xl bg-muted">{selected.imageUrl && <img src={selected.imageUrl} alt="" className="h-full w-full object-cover"/>}</div><div><div className="text-[10px] font-black uppercase tracking-[.12em] text-primary">{title}</div><h2 className="mt-1 text-2xl font-black">{selected.name}</h2><p className="mt-1 text-xs text-muted-foreground">{selected.collectionName || selected.baseName || 'DeckVerse'}</p><span className={`mt-3 inline-flex rounded-full border px-3 py-1 text-[10px] font-black ${active ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : 'border-amber-500/30 bg-amber-500/10 text-amber-300'}`}>{active ? 'ATIVO' : 'INATIVO'}</span></div></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><div><label className="text-xs font-black uppercase tracking-[.12em]">Sinopse</label><textarea value={draft} onChange={(e) => setDraft(e.target.value)} className="mt-2 min-h-[260px] w-full rounded-2xl border border-border bg-background p-4 text-sm leading-7" placeholder="Sinopse canônica..."/><div className="mt-2 text-right text-[10px] text-muted-foreground">{draft.length} caracteres</div></div><div className="space-y-4"><div><label className="text-xs font-black uppercase tracking-[.12em]">Imagem</label><label className="mt-2 flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-primary/40 bg-primary/5 p-5"><ImagePlus className="h-5 w-5 text-primary"/><span className="text-xs font-bold">{file?.name || 'Trocar imagem no Supabase Storage'}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="sr-only" onChange={(e) => setFile(e.target.files?.[0] || null)}/></label></div><label className="flex items-center justify-between rounded-2xl border border-border bg-background p-4"><span><strong className="block text-sm">Publicação</strong><span className="text-[10px] text-muted-foreground">Controla se aparece no catálogo.</span></span><input type="checkbox" checked={active} onChange={(e) => setActive(e.target.checked)} className="h-5 w-5"/></label><button disabled={busy} onClick={save} className="min-h-12 w-full rounded-xl bg-primary text-xs font-black text-primary-foreground disabled:opacity-50">{busy ? 'SALVANDO...' : 'SALVAR ALTERAÇÕES'}</button><Notice notice={notice}/></div></div></section>;
}

function ContentList({ title, rows, selected, query, setQuery, load, choose }) {
  return <aside className="rounded-3xl border border-border bg-card p-5"><h2 className="text-lg font-black">{title}</h2><div className="mt-4"><SearchBox query={query} setQuery={setQuery} load={load} placeholder={`Buscar ${title.toLowerCase()}`}/></div><div className="mt-4 max-h-[650px] space-y-2 overflow-y-auto">{rows.map((row) => <button key={row.id} onClick={() => choose(row)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected?.id === row.id ? 'border-primary bg-primary/10' : 'border-border bg-background'}`}><div className="h-14 w-11 overflow-hidden rounded-lg bg-muted">{row.imageUrl && <img src={row.imageUrl} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0"><div className="truncate text-xs font-black">{row.name}</div><div className="text-[9px] text-muted-foreground">{row.isActive === false ? 'Inativa' : 'Ativa'}{row.collectionName ? ` · ${row.collectionName}` : ''}</div></div></button>)}</div>{rows.length === 0 && <div className="py-8 text-center text-xs text-muted-foreground">Nenhum registro encontrado.</div>}</aside>;
}

function RecordsPanel({ kind, title, entityKind = kind }) {
  const [query, setQuery] = useState(''); const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [draft, setDraft] = useState(''); const [active, setActive] = useState(true); const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(null);
  const load = async () => { try { setNotice(null); const data = await searchSynopsisTargets(query, entityKind, 120); setRows(data); if (selected) { const next = data.find((x) => x.id === selected.id); if (next) { setSelected(next); setDraft(next.synopsis || ''); setActive(next.isActive !== false); } } } catch (e) { setNotice({ error: true, text: e.message }); } };
  useEffect(() => { load(); }, [kind]);
  const choose = (row) => { setSelected(row); setDraft(row.synopsis || ''); setActive(row.isActive !== false); setFile(null); setNotice(null); };
  const save = async () => { if (!selected) return; setBusy(true); setNotice(null); try { const image = file ? await uploadImage(selected, file, kind === 'collection' ? 'collection' : selected.entityType || 'form') : selected.imageUrl || null; if (kind === 'collection') await updateCollectionContent(selected.id, { synopsis: draft.trim(), is_active: active, cover_url: image }); else if (kind === 'form') await updateFormContent(selected.id, { synopsis: draft.trim(), is_active: active, image_url: image }); else await updateCardContent(selected.id, { synopsis: draft.trim(), is_active: active, image_url: image }); setNotice({ text: 'Alterações salvas com sucesso.' }); await load(); } catch (e) { setNotice({ error: true, text: e.message }); } finally { setBusy(false); } };
  return <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><ContentList title={title} rows={rows} selected={selected} query={query} setQuery={setQuery} load={load} choose={choose}/><Editor selected={selected} draft={draft} setDraft={setDraft} active={active} setActive={setActive} file={file} setFile={setFile} busy={busy} notice={notice} save={save} title={title}/></div>;
}

function PlayersPanel() {
  const [query, setQuery] = useState(''); const [players, setPlayers] = useState([]); const [selected, setSelected] = useState(null); const [status, setStatus] = useState('active'); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { setNotice(null); setPlayers(await searchAdminPlayers(query)); } catch (e) { setNotice({ error: true, text: e.message }); } };
  useEffect(() => { load(); }, []);
  const choose = (p) => { setSelected(p); setStatus(p.status || 'active'); setNotice(null); };
  const save = async () => { if (!selected) return; setBusy(true); setNotice(null); try { const row = await updatePlayerStatus(selected.id, status); setSelected(row); setPlayers((all) => all.map((p) => p.id === row.id ? row : p)); setNotice({ text: `Status alterado para ${STATUS[status]}.` }); } catch (e) { setNotice({ error: true, text: e.message }); } finally { setBusy(false); } };
  return <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><aside className="rounded-3xl border border-border bg-card p-5"><h2 className="text-lg font-black">Jogadores</h2><div className="mt-4"><SearchBox query={query} setQuery={setQuery} load={load} placeholder="Discord, usuário ou nome"/></div><div className="mt-4 max-h-[650px] space-y-2 overflow-y-auto">{players.map((p) => <button key={p.id} onClick={() => choose(p)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected?.id === p.id ? 'border-primary bg-primary/10' : 'border-border bg-background'}`}><div className="h-10 w-10 overflow-hidden rounded-xl bg-muted">{p.avatar_url && <img src={p.avatar_url} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0"><div className="truncate text-xs font-black">{p.display_name || p.discord_username || 'Jogador'}</div><div className="text-[9px] text-muted-foreground">{p.discord_username || p.discord_id || 'Conta'} · {STATUS[p.status] || p.status}</div></div></button>)}</div></aside><section className="rounded-3xl border border-border bg-card p-6">{!selected ? <div className="flex min-h-[560px] items-center justify-center text-center"><div><Users className="mx-auto h-10 w-10 text-muted-foreground/30"/><h3 className="mt-4 text-xl font-black">Selecione um jogador</h3></div></div> : <div className="max-w-xl"><div className="flex items-center gap-4"><div className="h-20 w-20 overflow-hidden rounded-2xl bg-muted">{selected.avatar_url && <img src={selected.avatar_url} alt="" className="h-full w-full object-cover"/>}</div><div><h2 className="text-2xl font-black">{selected.display_name || selected.discord_username || 'Jogador'}</h2><p className="text-xs text-muted-foreground">Nível {selected.level ?? 0} · PWR {selected.pwr ?? 0}</p></div></div><div className="mt-8"><label className="text-xs font-black uppercase tracking-[.12em]">Status da conta</label><div className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(STATUS).map(([key, label]) => <button key={key} onClick={() => setStatus(key)} className={`rounded-xl border px-4 py-4 text-xs font-black ${status === key ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-background'}`}>{label}</button>)}</div><button disabled={busy} onClick={save} className="mt-4 min-h-12 w-full rounded-xl bg-primary text-xs font-black text-primary-foreground disabled:opacity-50">{busy ? 'SALVANDO...' : 'SALVAR STATUS'}</button><div className="mt-4"><Notice notice={notice}/></div></div></div>}</section></div>;
}

export default function AdminContentCenter() {
  const [tab, setTab] = useState('collections');
  const tabs = [['collections', 'Coleções', BookOpen], ['cards', 'Cartas', Sparkles], ['forms', 'Formas', ImagePlus], ['players', 'Jogadores', Users]];
  return <div className="min-h-screen bg-background text-foreground"><Navbar/><main className="mx-auto w-full max-w-[1480px] px-4 pb-28 pt-7 sm:px-6 lg:px-8"><section className="rounded-[2rem] border border-primary/25 bg-card p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-primary"><ShieldCheck className="h-4 w-4"/> Administração · Conteúdo</div><h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-5xl">Central de Conteúdo</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Edite capas, artes, sinopses, formas e status de jogadores. Imagens são armazenadas no Supabase Storage e alterações administrativas são protegidas por RPC.</p><div className="mt-6 flex flex-wrap gap-2">{tabs.map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`flex min-h-11 items-center gap-2 rounded-xl border px-4 text-xs font-black ${tab === key ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-background text-muted-foreground'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div></section><section className="mt-6">{tab === 'collections' && <RecordsPanel kind="collection" title="Coleções" entityKind="collection"/>}{tab === 'cards' && <CardsSelector/>}{tab === 'forms' && <RecordsPanel kind="form" title="Formas evolutivas" entityKind="form"/>}{tab === 'players' && <PlayersPanel/>}</section></main></div>;
}

function CardsSelector() {
  const [kind, setKind] = useState('character');
  return <div><div className="mb-4 flex flex-wrap gap-2">{CARD_KINDS.map(([key, label]) => <button key={key} onClick={() => setKind(key)} className={`rounded-xl border px-4 py-3 text-xs font-black ${kind === key ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-card text-muted-foreground'}`}>{label}</button>)}</div><RecordsPanel kind={kind} title={CARD_KINDS.find(([key]) => key === kind)?.[1] || 'Cartas'} entityKind={kind}/></div>;
}
