import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, ImagePlus, Link2, Search, ShieldCheck, Sparkles, UploadCloud, Users, X } from 'lucide-react';
import Navbar from './Navbar';
import { getSupabaseBrowserClient } from './services/supabase/client.js';
import { searchAdminPlayers, searchSynopsisTargets, updateCardContent, updateCollectionContent, updateFormContent, updatePlayerStatus } from './services/supabase/adminService.js';

const STATUS = { active: 'Ativo', suspended: 'Suspenso', banned: 'Banido' };
const CARD_KINDS = [['all', 'Todas'], ['character', 'Personagens'], ['item', 'Itens'], ['boss', 'Bosses']];
const slug = (value) => String(value || 'item').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'item';
const labelFor = (type) => ({ collection: 'Coleção', character: 'Personagem', item: 'Item', boss: 'Boss', form: 'Forma' }[type] || type);

async function uploadImage(entity, file, type) {
  if (!file) return entity.imageUrl || '';
  const supabase = getSupabaseBrowserClient();
  const collection = String(entity.collectionId || (type === 'collection' ? entity.id : 'MULTIVERSE')).toUpperCase();
  const extRaw = (file.name.split('.').pop() || 'jpg').toLowerCase();
  const ext = extRaw === 'jpeg' ? 'jpg' : extRaw;
  const path = `deckverse-media/${collection}/${type}/${collection}__${type}__${slug(entity.name)}.${ext}`;
  const { error } = await supabase.storage.from('cards').upload(path, file, { upsert: true, contentType: file.type, cacheControl: '31536000' });
  if (error) throw error;
  return supabase.storage.from('cards').getPublicUrl(path).data.publicUrl;
}

function Notice({ notice }) {
  if (!notice) return null;
  return <div className={`rounded-xl border p-3 text-xs ${notice.error ? 'border-destructive/30 bg-destructive/10 text-destructive' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'}`}>{notice.text}</div>;
}

function SearchBox({ query, setQuery, load, placeholder }) {
  return <div className="flex gap-2"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder={placeholder} className="h-11 w-full rounded-xl border border-border bg-background pl-9 pr-3 text-sm outline-none focus:border-primary/60"/></label><button onClick={load} aria-label="Buscar" className="h-11 w-11 shrink-0 rounded-xl bg-primary text-primary-foreground"><Search className="mx-auto h-4 w-4"/></button></div>;
}

function ImageDropZone({ entity, file, setFile, imageUrl, setImageUrl }) {
  const [dragging, setDragging] = useState(false);
  const [mode, setMode] = useState('upload');
  const accept = (candidate) => {
    if (!candidate || !candidate.type?.startsWith('image/')) return;
    setFile(candidate);
    setImageUrl('');
  };
  const preview = file ? URL.createObjectURL(file) : (imageUrl || entity.imageUrl);
  return <div>
    <div className="flex items-center justify-between gap-3"><label className="text-xs font-black uppercase tracking-[.12em]">Imagem</label><div className="flex gap-1 rounded-lg border border-border bg-background p-1"><button type="button" onClick={() => setMode('upload')} className={`rounded-md px-2 py-1 text-[9px] font-black ${mode === 'upload' ? 'bg-primary/10 text-primary' : 'text-muted-foreground'}`}><UploadCloud className="mr-1 inline h-3 w-3"/>Upload</button><button type="button" onClick={() => setMode('link')} className={`rounded-md px-2 py-1 text-[9px] font-black ${mode === 'link' ? 'bg-primary/10 text-primary' : 'text-muted-foreground'}`}><Link2 className="mr-1 inline h-3 w-3"/>Link</button></div></div>
    {mode === 'upload' ? <label onDragEnter={(e) => { e.preventDefault(); setDragging(true); }} onDragOver={(e) => e.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={(e) => { e.preventDefault(); setDragging(false); accept(e.dataTransfer.files?.[0]); }} className={`mt-2 flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed p-5 text-center transition ${dragging ? 'border-primary bg-primary/10' : 'border-primary/35 bg-primary/5 hover:border-primary/60'}`}><UploadCloud className="h-7 w-7 text-primary"/><span className="mt-2 text-xs font-black">Arraste a imagem aqui</span><span className="mt-1 text-[10px] text-muted-foreground">ou clique para selecionar como upload comum</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="sr-only" onChange={(e) => accept(e.target.files?.[0])}/></label> : <div className="mt-2 rounded-2xl border border-border bg-background p-3"><div className="flex items-center gap-2"><Link2 className="h-4 w-4 text-primary"/><input value={imageUrl} onChange={(e) => { setImageUrl(e.target.value); setFile(null); }} placeholder="https://.../imagem.jpg" className="h-10 min-w-0 flex-1 bg-transparent text-xs outline-none"/></div><p className="mt-2 text-[9px] leading-4 text-muted-foreground">O link será salvo como fonte da imagem. Para armazenar uma cópia no Supabase Storage, use Upload.</p></div>}
    {(file || imageUrl) && <div className="mt-3 flex items-center gap-3 rounded-xl border border-border bg-background p-2"><div className="h-16 w-12 overflow-hidden rounded-lg bg-muted">{preview && <img src={preview} alt="Prévia" className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><div className="truncate text-[10px] font-black">{file?.name || imageUrl}</div><div className="text-[9px] text-muted-foreground">Nova imagem</div></div><button type="button" onClick={() => { setFile(null); setImageUrl(''); }} className="rounded-lg p-2 text-muted-foreground hover:text-foreground"><X className="h-4 w-4"/></button></div>}
  </div>;
}

function Editor({ selected, draft, setDraft, active, setActive, file, setFile, imageUrl, setImageUrl, busy, notice, save, title }) {
  if (!selected) return <section className="rounded-3xl border border-border bg-card"><div className="flex min-h-[560px] items-center justify-center p-6 text-center text-muted-foreground"><div><ImagePlus className="mx-auto h-10 w-10 opacity-30"/><h3 className="mt-4 text-xl font-black text-foreground">Selecione um registro</h3><p className="mt-2 text-sm">Imagem, sinopse e publicação ficam editáveis aqui.</p></div></div></section>;
  const max = selected.entityType === 'collection' ? 400 : selected.entityType === 'form' ? 220 : 500;
  return <section className="rounded-3xl border border-border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-start"><div className="h-36 w-28 shrink-0 overflow-hidden rounded-2xl bg-muted"><img src={imageUrl || selected.imageUrl || ''} alt="" className="h-full w-full object-cover"/></div><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.12em] text-primary"><ShieldCheck className="h-3.5 w-3.5"/> {title}</div><h2 className="mt-1 text-2xl font-black">{selected.name}</h2><p className="mt-1 text-xs text-muted-foreground">{selected.collectionName || selected.baseName || 'DeckVerse'}{selected.rarity ? ` · ${selected.rarity}` : ''}</p><span className={`mt-3 inline-flex rounded-full border px-3 py-1 text-[10px] font-black ${active ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : 'border-amber-500/30 bg-amber-500/10 text-amber-300'}`}>{active ? 'ATIVO' : 'INATIVO'}</span></div></div><div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_330px]"><div><div className="flex items-center justify-between gap-3"><label className="text-xs font-black uppercase tracking-[.12em]">Sinopse</label><span className="text-[10px] font-black text-muted-foreground">{draft.length}/{max} · vazio permitido</span></div><textarea value={draft} maxLength={max} onChange={(e) => setDraft(e.target.value)} className="mt-2 min-h-[290px] w-full rounded-2xl border border-border bg-background p-4 text-sm leading-7 outline-none focus:border-primary/60" placeholder="Deixe vazio se não quiser uma sinopse."/><div className="mt-2 text-[10px] text-muted-foreground">Sem mínimo de caracteres. Somente o limite máximo é aplicado.</div></div><div className="space-y-5"><ImageDropZone entity={selected} file={file} setFile={setFile} imageUrl={imageUrl} setImageUrl={setImageUrl}/><label className="flex items-center justify-between rounded-2xl border border-border bg-background p-4"><span><strong className="block text-sm">Publicação</strong><span className="text-[10px] text-muted-foreground">Controla se aparece no catálogo.</span></span><input type="checkbox" checked={active} onChange={(e) => setActive(e.target.checked)} className="h-5 w-5"/></label><button disabled={busy} onClick={save} className="min-h-12 w-full rounded-xl bg-primary text-xs font-black text-primary-foreground disabled:opacity-50">{busy ? 'SALVANDO...' : 'SALVAR ALTERAÇÕES'}</button><Notice notice={notice}/></div></div></section>;
}

function groupRows(rows) {
  const groups = new Map();
  rows.forEach((row) => { const key = row.entityType === 'collection' ? 'Coleções' : (row.collectionName || 'Sem coleção'); if (!groups.has(key)) groups.set(key, []); groups.get(key).push(row); });
  return [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0], 'pt-BR', { sensitivity: 'base' })).map(([name, items]) => [name, items.sort((a, b) => String(a.name).localeCompare(String(b.name), 'pt-BR', { sensitivity: 'base' }))]);
}

function RecordsPanel({ entityKind, title, grouped = false }) {
  const [query, setQuery] = useState(''); const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [draft, setDraft] = useState(''); const [active, setActive] = useState(true); const [file, setFile] = useState(null); const [imageUrl, setImageUrl] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(null);
  const load = async () => { try { setNotice(null); const data = await searchSynopsisTargets(query, entityKind, 300); setRows(data); if (selected) { const next = data.find((x) => x.id === selected.id && x.scope === selected.scope); if (next) { setSelected(next); setDraft(next.synopsis || ''); setActive(next.isActive !== false); } } } catch (e) { setNotice({ error: true, text: e.message }); } };
  useEffect(() => { load(); }, [entityKind]);
  const choose = (row) => { setSelected(row); setDraft(row.synopsis || ''); setActive(row.isActive !== false); setFile(null); setImageUrl(''); setNotice(null); };
  const save = async () => { if (!selected) return; setBusy(true); setNotice(null); try { const image = file ? await uploadImage(selected, file, selected.entityType === 'collection' ? 'collection' : selected.entityType) : (imageUrl.trim() || selected.imageUrl || null); const payload = { synopsis: draft.trim(), is_active: active }; if (selected.entityType === 'collection') await updateCollectionContent(selected.id, { ...payload, cover_url: image }); else if (selected.entityType === 'form') await updateFormContent(selected.id, { ...payload, image_url: image }); else await updateCardContent(selected.id, { ...payload, image_url: image }); setNotice({ text: 'Alterações salvas com sucesso.' }); await load(); } catch (e) { setNotice({ error: true, text: e.message }); } finally { setBusy(false); } };
  const groups = useMemo(() => grouped ? groupRows(rows) : [['', rows]], [grouped, rows]);
  return <div className="grid gap-5 xl:grid-cols-[430px_1fr]"><aside className="rounded-3xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-[10px] text-muted-foreground">{rows.length} registro(s)</p></div><span className="rounded-lg border border-border px-2 py-1 text-[9px] font-black text-muted-foreground">A–Z</span></div><div className="mt-4"><SearchBox query={query} setQuery={setQuery} load={load} placeholder="Nome, letra ou raridade..."/></div><p className="mt-2 text-[9px] leading-4 text-muted-foreground">Busca vazia mostra tudo. Digite nome, letra ou raridade para filtrar.</p><div className="mt-4 max-h-[720px] space-y-4 overflow-y-auto pr-1">{groups.map(([group, items]) => <div key={group || 'all'}>{group && <div className="sticky top-0 z-10 mb-2 rounded-lg bg-card py-2 text-[10px] font-black uppercase tracking-[.12em] text-primary">{group} <span className="text-muted-foreground">· {items.length}</span></div>}<div className="space-y-2">{items.map((row) => <button key={`${row.scope}:${row.id}`} onClick={() => choose(row)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected?.id === row.id && selected?.scope === row.scope ? 'border-primary bg-primary/10' : 'border-border bg-background hover:border-primary/35'}`}><div className="h-14 w-11 shrink-0 overflow-hidden rounded-lg bg-muted"><img src={row.imageUrl || ''} alt="" className="h-full w-full object-cover"/></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{row.name}</div><div className="mt-1 truncate text-[9px] text-muted-foreground">{labelFor(row.entityType)}{row.rarity ? ` · ${row.rarity}` : ''}</div></div></button>)}</div></div>)}{rows.length === 0 && <div className="py-12 text-center text-xs text-muted-foreground">Nenhum registro encontrado.</div>}</div></aside><Editor selected={selected} draft={draft} setDraft={setDraft} active={active} setActive={setActive} file={file} setFile={setFile} imageUrl={imageUrl} setImageUrl={setImageUrl} busy={busy} notice={notice} save={save} title={title}/></div>;
}

function PlayersPanel() {
  const [query, setQuery] = useState(''); const [players, setPlayers] = useState([]); const [selected, setSelected] = useState(null); const [status, setStatus] = useState('active'); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { setNotice(null); setPlayers(await searchAdminPlayers(query)); } catch (e) { setNotice({ error: true, text: e.message }); } };
  useEffect(() => { load(); }, []);
  const choose = (p) => { setSelected(p); setStatus(p.status || 'active'); setNotice(null); };
  const save = async () => { if (!selected) return; setBusy(true); setNotice(null); try { const row = await updatePlayerStatus(selected.id, status); setSelected(row); setPlayers((all) => all.map((p) => p.id === row.id ? row : p)); setNotice({ text: `Status alterado para ${STATUS[status]}.` }); } catch (e) { setNotice({ error: true, text: e.message }); } finally { setBusy(false); } };
  return <div className="grid gap-5 xl:grid-cols-[430px_1fr]"><aside className="rounded-3xl border border-border bg-card p-5"><h2 className="text-lg font-black">Jogadores</h2><div className="mt-4"><SearchBox query={query} setQuery={setQuery} load={load} placeholder="Discord, usuário ou nome"/></div><div className="mt-4 max-h-[720px] space-y-2 overflow-y-auto">{players.map((p) => <button key={p.id} onClick={() => choose(p)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected?.id === p.id ? 'border-primary bg-primary/10' : 'border-border bg-background'}`}><div className="h-10 w-10 overflow-hidden rounded-xl bg-muted"><img src={p.avatar_url || ''} alt="" className="h-full w-full object-cover"/></div><div className="min-w-0"><div className="truncate text-xs font-black">{p.display_name || p.discord_username || 'Jogador'}</div><div className="text-[9px] text-muted-foreground">{p.discord_username || p.discord_id || 'Conta'} · {STATUS[p.status] || p.status}</div></div></button>)}</div></aside><section className="rounded-3xl border border-border bg-card p-6">{!selected ? <div className="flex min-h-[560px] items-center justify-center text-center"><div><Users className="mx-auto h-10 w-10 text-muted-foreground/30"/><h3 className="mt-4 text-xl font-black">Selecione um jogador</h3></div></div> : <div className="max-w-xl"><div className="flex items-center gap-4"><div className="h-20 w-20 overflow-hidden rounded-2xl bg-muted"><img src={selected.avatar_url || ''} alt="" className="h-full w-full object-cover"/></div><div><h2 className="text-2xl font-black">{selected.display_name || selected.discord_username || 'Jogador'}</h2><p className="text-xs text-muted-foreground">Nível {selected.level ?? 0} · PWR {selected.pwr ?? 0}</p></div></div><div className="mt-8"><label className="text-xs font-black uppercase tracking-[.12em]">Status da conta</label><div className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(STATUS).map(([key, label]) => <button key={key} onClick={() => setStatus(key)} className={`rounded-xl border px-4 py-4 text-xs font-black ${status === key ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-background'}`}>{label}</button>)}</div><button disabled={busy} onClick={save} className="mt-4 min-h-12 w-full rounded-xl bg-primary text-xs font-black text-primary-foreground disabled:opacity-50">{busy ? 'SALVANDO...' : 'SALVAR STATUS'}</button><div className="mt-4"><Notice notice={notice}/></div></div></div>}</section></div>;
}

export default function AdminContentCenter() {
  const [tab, setTab] = useState('collections');
  const tabs = [['collections', 'Coleções', BookOpen], ['cards', 'Cartas', Sparkles], ['forms', 'Formas', ImagePlus], ['players', 'Jogadores', Users]];
  return <div className="min-h-screen bg-background text-foreground"><Navbar/><main className="mx-auto w-full max-w-[1560px] px-4 pb-28 pt-7 sm:px-6 lg:px-8"><section className="rounded-[2rem] border border-primary/25 bg-card p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-primary"><ShieldCheck className="h-4 w-4"/> Administração · Conteúdo</div><h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-5xl">Central de Conteúdo</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-muted-foreground">Edite imagens, sinopses e publicação de coleções, personagens, itens, bosses e formas. Cartas ficam agrupadas por coleção e em ordem alfabética. A busca aceita nome, letra ou raridade.</p><div className="mt-6 flex flex-wrap gap-2">{tabs.map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`flex min-h-11 items-center gap-2 rounded-xl border px-4 text-xs font-black ${tab === key ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-background text-muted-foreground'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div></section><section className="mt-6">{tab === 'collections' && <RecordsPanel entityKind="collection" title="Coleções"/>}{tab === 'cards' && <CardsPanel/>}{tab === 'forms' && <RecordsPanel entityKind="form" title="Formas evolutivas" grouped/>}{tab === 'players' && <PlayersPanel/>}</section></main></div>;
}

function CardsPanel() {
  const [kind, setKind] = useState('all');
  return <div><div className="mb-4 flex flex-wrap gap-2">{CARD_KINDS.map(([key, label]) => <button key={key} onClick={() => setKind(key)} className={`rounded-xl border px-4 py-3 text-xs font-black ${kind === key ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-card text-muted-foreground'}`}>{label}</button>)}</div><RecordsPanel key={kind} entityKind={kind} title={kind === 'all' ? 'Cartas' : labelFor(kind) + 's'} grouped/></div>;
}
