import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpen, Gem, Layers, Package, Search, ShieldCheck, Sparkles, Swords, UserRound } from 'lucide-react';
import Navbar from './Navbar';
import DeckVerseLogo from './DeckVerseLogo';
import { loadCatalogSnapshot } from './services/catalog/catalogDataService.js';
import { deriveCatalogForms } from './services/catalog/catalogFormsService.js';

const getImage = (entity) => entity?.image_url || entity?.imageUrl || entity?.cover_url || '';
const getName = (entity) => entity?.name || entity?.title || 'Sem nome';

function CatalogCount({ icon: Icon, label, value, href }) { return <Link to={href} className="group flex min-h-16 items-center justify-between gap-4 border-b border-border px-4 py-3 transition hover:bg-muted/40 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4"/></div><div><div className="text-sm font-extrabold">{label}</div><div className="text-[11px] text-muted-foreground">No códice atual</div></div></div><div className="flex items-center gap-2"><span className="text-xl font-black">{value}</span><ArrowRight className="h-4 w-4 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary"/></div></Link>; }
function CollectionTile({collection}) { const name=getName(collection), key=collection?.id||collection?.code||name, image=getImage(collection); return <Link to={`/collections/${encodeURIComponent(key)}`} className="group relative min-h-[230px] overflow-hidden rounded-2xl border border-border bg-card transition hover:-translate-y-0.5 hover:border-primary/45">{image?<img src={image} alt={name} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]"/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_top,hsl(var(--primary)/.18),transparent_62%)]"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/94 via-black/40 to-black/8"/><div className="absolute inset-x-4 bottom-4"><div className="text-[10px] font-extrabold uppercase tracking-[.16em] text-white/55">{collection?.category||'Coleção'}</div><h3 className="mt-1 text-lg font-black text-white">{name}</h3>{collection?.synopsis&&<p className="mt-2 line-clamp-2 text-[11px] leading-5 text-white/65">{collection.synopsis}</p>}</div></Link>; }
function CharacterTile({entity}) { const name=getName(entity), image=getImage(entity); return <Link to={entity?.id?`/card/${encodeURIComponent(entity.id)}`:'/characters'} className="group overflow-hidden rounded-2xl border border-border bg-card transition hover:-translate-y-0.5 hover:border-primary/45"><div className="relative aspect-[4/5] overflow-hidden bg-muted">{image?<img src={image} alt={name} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.025]"/>:<div className="absolute inset-0 flex items-center justify-center"><UserRound className="h-8 w-8 text-muted-foreground/30"/></div>}<div className="absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-black/94 to-transparent"/><div className="absolute inset-x-3 bottom-3"><h3 className="line-clamp-2 text-sm font-extrabold leading-tight text-white">{name}</h3><p className="mt-1 truncate text-[10px] text-white/60">{entity?.series||entity?.collection||'DeckVerse'}</p></div></div></Link>; }

export default function Home() {
  const [query,setQuery]=useState(''); const navigate=useNavigate();
  const snapshotQuery=useQuery({queryKey:['catalog-snapshot-canonical'],queryFn:loadCatalogSnapshot,staleTime:5*60_000});
  const snapshot=snapshotQuery.data||{collections:[],characters:[],items:[],bosses:[]};
  const collections=snapshot.collections||[], characters=snapshot.characters||[], items=snapshot.items||[], bosses=snapshot.bosses||[];
  const forms=useMemo(()=>deriveCatalogForms(snapshot),[snapshot]);
  const uniqueCollections=useMemo(()=>{const seen=new Set();return collections.filter(e=>{const k=String(e?.id||e?.name||'').toLowerCase();if(!k||seen.has(k))return false;seen.add(k);return true;});},[collections]);
  const featuredCollections=uniqueCollections.slice(0,6), recentCharacters=characters.slice(0,8), isLoading=snapshotQuery.isLoading;
  const handleSearch=(event)=>{event.preventDefault();const value=query.trim();navigate(value?`/characters?search=${encodeURIComponent(value)}`:'/characters');};

  return <div className="min-h-screen bg-background text-foreground"><Navbar/><main className="mx-auto w-full max-w-[1480px] px-4 pb-28 sm:px-6 lg:px-8">
    <section className="relative overflow-hidden py-12 sm:py-16 lg:py-20"><div className="pointer-events-none absolute inset-0 archive-grid opacity-45"/><div className="relative mx-auto max-w-5xl text-center"><div className="mb-6 flex justify-center"><DeckVerseLogo size="lg" showTagline/></div><div className="mx-auto mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-card/70 px-3 py-1.5 text-[11px] font-extrabold uppercase tracking-[.16em] text-muted-foreground"><BookOpen className="h-3.5 w-3.5 text-primary"/> Códice multiversal</div><h1 className="mx-auto max-w-4xl text-4xl font-black tracking-[-.055em] sm:text-6xl lg:text-7xl">Colecione histórias. <span className="text-primary">Explore universos.</span></h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-muted-foreground sm:text-base">Personagens, formas, bosses e relíquias são apresentados pela identidade canônica, raridade colecionável e lore — sem ATK, DEF, HP ou escala numérica de poder.</p>
      <form onSubmit={handleSearch} className="mx-auto mt-8 flex max-w-2xl gap-2 rounded-2xl border border-border bg-card/90 p-2"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input aria-label="Buscar no DeckVerse" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque personagem, forma, item, boss ou universo" className="h-12 w-full rounded-xl bg-transparent pl-10 pr-3 text-sm outline-none"/></label><button type="submit" className="min-h-12 rounded-xl bg-primary px-5 text-sm font-black text-primary-foreground">Buscar</button></form>
      <div className="mt-5 flex flex-wrap items-center justify-center gap-2"><Link to="/collections" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-primary-foreground"><BookOpen className="h-4 w-4"/> Abrir códice</Link><Link to="/gacha" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border bg-card px-4 text-sm font-extrabold"><Gem className="h-4 w-4 text-primary"/> Invocar</Link><Link to="/my-collection" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border bg-card px-4 text-sm font-extrabold"><ShieldCheck className="h-4 w-4 text-secondary"/> Meu acervo</Link></div></div></section>

    <section className="overflow-hidden rounded-2xl border border-border bg-card/80"><div className="border-b border-border px-5 py-4"><div className="text-xs font-extrabold uppercase tracking-[.16em] text-primary">Catálogo</div><h2 className="mt-1 text-lg font-black">Visão geral do códice</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-5"><CatalogCount icon={Layers} label="Coleções" value={isLoading?'—':uniqueCollections.length} href="/collections"/><CatalogCount icon={UserRound} label="Personagens" value={isLoading?'—':characters.length} href="/characters"/><CatalogCount icon={Sparkles} label="Formas" value={isLoading?'—':forms.length} href="/forms"/><CatalogCount icon={Package} label="Itens" value={isLoading?'—':items.length} href="/items"/><CatalogCount icon={Swords} label="Bosses" value={isLoading?'—':bosses.length} href="/bosses"/></div></section>

    <section className="mt-12"><div className="mb-5 flex items-end justify-between"><div><div className="text-xs font-extrabold uppercase tracking-[.16em] text-primary">Coleções</div><h2 className="mt-1 text-2xl font-black">Explore por universo</h2></div><Link to="/collections" className="text-sm font-extrabold text-muted-foreground hover:text-primary">Ver todas →</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featuredCollections.map(c=><CollectionTile key={c.id||getName(c)} collection={c}/>)}</div></section>
    <section className="mt-12"><div className="mb-5 flex items-end justify-between"><div><div className="text-xs font-extrabold uppercase tracking-[.16em] text-secondary">Personagens</div><h2 className="mt-1 text-2xl font-black">No catálogo atual</h2></div><Link to="/characters" className="text-sm font-extrabold text-muted-foreground hover:text-primary">Ver personagens →</Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{recentCharacters.map(e=><CharacterTile key={e.id||getName(e)} entity={e}/>)}</div></section>
  </main></div>;
}
