import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowLeft, Compass, Home, Search } from 'lucide-react';
import Navbar from './Navbar';

export default function PageNotFound() {
  const location = useLocation();
  const pageName = location.pathname || '/';

  return <div className="min-h-screen bg-background text-foreground"><Navbar /><main className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-[1480px] items-center justify-center px-5 pb-28 pt-8 sm:px-6 lg:px-8"><section className="relative w-full max-w-2xl overflow-hidden rounded-[2rem] border border-border bg-card p-7 text-center shadow-2xl sm:p-12"><div className="pointer-events-none absolute inset-0 archive-grid opacity-20" /><div className="relative"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl border border-primary/25 bg-primary/10 text-primary"><Compass className="h-7 w-7" /></div><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-primary">DeckVerse · rota ausente</p><div className="mt-2 text-7xl font-black tracking-[-.08em] sm:text-8xl">404</div><h1 className="mt-2 text-2xl font-black sm:text-3xl">Página não encontrada</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-muted-foreground">O endereço <code className="rounded-md border border-border bg-background px-1.5 py-0.5 text-xs text-foreground">{pageName}</code> não corresponde a uma página disponível no códice atual.</p><div className="mt-7 flex flex-col justify-center gap-2 sm:flex-row"><Link to="/" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-black text-primary-foreground"><Home className="h-4 w-4" /> Ir para o início</Link><Link to="/characters" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border bg-background px-5 text-sm font-extrabold"><Search className="h-4 w-4" /> Pesquisar catálogo</Link><button type="button" onClick={() => window.history.back()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border bg-background px-5 text-sm font-extrabold"><ArrowLeft className="h-4 w-4" /> Voltar</button></div></div></section></main></div>;
}
