import assert from 'node:assert/strict';
import { createPurchaseMarketListingUseCase } from '../../services/useCases/purchaseMarketListing.js';
import { createCreateMarketListingUseCase } from '../../services/useCases/createMarketListing.js';
import { createCancelMarketListingUseCase } from '../../services/useCases/cancelMarketListing.js';
const calls=[];const repo={buyListing:async(...a)=>{calls.push(['buy',...a]);return {ok:true};},createListing:async(...a)=>{calls.push(['create',...a]);return {ok:true};},cancelListing:async id=>{calls.push(['cancel',id]);return {ok:true};}};
const tx='550e8400-e29b-41d4-a716-446655440000';
await createPurchaseMarketListingUseCase(repo).execute('l1',tx);
await createCreateMarketListingUseCase(repo).execute('c1','2','500');
await createCancelMarketListingUseCase(repo).execute('l1');
assert.deepEqual(calls,[['buy','l1',tx],['create','c1',2,500],['cancel','l1']]);
await assert.rejects(()=>createCreateMarketListingUseCase(repo).execute('',1,1),/INVALID_LISTING/);
await assert.rejects(()=>createPurchaseMarketListingUseCase(repo).execute(''),/LISTING_REQUIRED/);
console.log('marketplace use cases: ok');
